import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { isSafari } from "../../utils/getBrowser";
import BtnScroll from "../Buttons/BtnScroll";
import Footer from "../Footer/Footer";
import Navbar from "../NavBar/Navbar";

interface WrapperProps {
    children: React.ReactNode;
    title: string;
}

const Layout: React.FC<WrapperProps> = ({children, title}) => {
    const[btnColor, setBtnColor] = useState("text-stratos");
    const[isVisible, setIsVisible] = useState(false);
    const footerRef = useRef<HTMLDivElement>(null);
    const navRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        window.addEventListener("scroll", () => handleScroll());
        return () => window.removeEventListener("scroll", () => handleScroll());
    }, []);

    const handleScroll = () => {
        const scrollTop = isSafari() ? document.documentElement.scrollTop : document.body.scrollTop;
        if (navRef.current && footerRef.current) {
            if (scrollTop > navRef.current.offsetHeight) {
                setIsVisible(true);
                var footerHeight = footerRef.current.offsetHeight;
                var distanceToBottom = document.body.scrollHeight - scrollTop - window.innerHeight;

                if (distanceToBottom < footerHeight) {
                    setBtnColor("text-white");
                } else {
                    setBtnColor("text-stratos");
                }
            } else {
                setIsVisible(false);
            }
        }
    }

    return(
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand" />
            </Head>
            <BtnScroll isVisible={isVisible} btnColor={btnColor} />
            <Navbar title={title} ref={navRef} />
            {children}
            <Footer ref={footerRef} />
        </div>
    )
}

export default Layout;