import Head from "next/head";
import Footer from "../Footer";
import Navbar from "../Navbar";

interface WrapperProps {
    children: React.ReactNode;
    title: string;
}

const Layout: React.FC<WrapperProps> = ({children, title}) => {
    return(
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar title={title} />
            {children}
            <Footer />
        </div>
    )
}

export default Layout;